/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artist/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist Songs */
        get: operations["get_artist_songs_artist_songs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/{chart_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Chart */
        get: operations["get_latest_chart_charts__chart_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/history/{chart_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chart History */
        get: operations["get_chart_history_charts_history__chart_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Song Stream Report History */
        get: operations["get_song_stream_report_history_reports_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtistSongsResponse */
        ArtistSongsResponse: {
            /** Artist Id */
            artist_id: string;
            /** Songs */
            songs: components["schemas"]["SongResponse"][];
        };
        /** ChartEntryResponse */
        ChartEntryResponse: {
            song: components["schemas"]["SongResponse"];
            snapshot: components["schemas"]["SongChartSnapshotResponse"];
        };
        /** ChartHistoryEntryResponse */
        ChartHistoryEntryResponse: {
            song: components["schemas"]["SongResponse"];
            /** Snapshots */
            snapshots: components["schemas"]["ChartHistorySnapshotResponse"][];
        };
        /** ChartHistoryResponse */
        ChartHistoryResponse: {
            chart_type: components["schemas"]["ChartType"];
            entry: components["schemas"]["ChartHistoryEntryResponse"];
        };
        /** ChartHistorySnapshotResponse */
        ChartHistorySnapshotResponse: {
            /** Current Rank */
            current_rank: number;
            /**
             * Rank Day
             * Format: date
             */
            rank_day: string;
            /** Rank Hour */
            rank_hour: string | null;
        };
        /** ChartResponse */
        ChartResponse: {
            chart_type: components["schemas"]["ChartType"];
            /** Entries */
            entries: components["schemas"]["ChartEntryResponse"][];
        };
        /**
         * ChartType
         * @description Which chart endpoint a SongChartSnapshot row came from.
         * @enum {string}
         */
        ChartType: "realtime" | "top100" | "daily" | "weekly" | "hot100";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SongChartSnapshotResponse */
        SongChartSnapshotResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Song Id */
            song_id: string;
            chart_type: components["schemas"]["ChartType"];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Rank Day
             * Format: date
             */
            rank_day: string;
            /** Rank Hour */
            rank_hour: string | null;
            /** Current Rank */
            current_rank: number;
            /** Past Rank */
            past_rank: number;
            /** Rank Gap */
            rank_gap: number;
            /** Rank Type */
            rank_type: string;
        };
        /** SongResponse */
        SongResponse: {
            /** Song Id */
            song_id: string;
            /** Title */
            title: string;
            /** Album Id */
            album_id: string | null;
            /** Album Name */
            album_name: string | null;
            /** Album Cover Url */
            album_cover_url: string | null;
            /** Play Time */
            play_time: number | null;
            /** Issue Date */
            issue_date: string | null;
            /** Is Title Song */
            is_title_song: boolean | null;
        };
        /** SongStreamReportHistoryResponse */
        SongStreamReportHistoryResponse: {
            /** Song Id */
            song_id: string;
            /** Snapshots */
            snapshots: components["schemas"]["SongStreamReportSnapshotResponse"][];
        };
        /** SongStreamReportSnapshotResponse */
        SongStreamReportSnapshotResponse: {
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /** Daily Listener Count */
            daily_listener_count: number | null;
            /** Total Listen Count */
            total_listen_count: number | null;
            /** Total Listener Count */
            total_listener_count: number | null;
            /** Male Percent */
            male_percent: string | null;
            /** Female Percent */
            female_percent: string | null;
            /** Yesterday Rank */
            yesterday_rank: number | null;
            /** Age Percent */
            age_percent: number[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artist_songs_artist_songs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistSongsResponse"];
                };
            };
        };
    };
    get_latest_chart_charts__chart_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chart_type: components["schemas"]["ChartType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_history_charts_history__chart_type__get: {
        parameters: {
            query: {
                songId: string;
            };
            header?: never;
            path: {
                chart_type: components["schemas"]["ChartType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_song_stream_report_history_reports_history_get: {
        parameters: {
            query: {
                songId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongStreamReportHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
